version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restipe
    volumes:
      - ./db/default:/db/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -d restipe
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 3s

  restipe:
    restart: on-failure
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
