version: '3'
services:
  db:
    build: 
      context: ./db
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restipe
    volumes:
     - ./db/default:/db/data


  restipe:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db