port: "8000"
jwttoken: "_yourprivatejwttoken_"
images_path: "images"

db:
    username: "postgres"
    password: "postgres"
    host:     "db"
    port:     "5432"
    dbname:   "restipe"
    ssl:      "disable"